name: Deploy VitePress Docs to GitHub Pages

on:
  push:
    branches:
      - main # 在 main 分支推送时触发
    paths:
      - "docs/**" # 仅在 docs 目录下的文件发生更改时触发
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build VitePress Site
        run: yarn build

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          clean: false # 保留 gh-pages 分支的内容

      - name: Copy build output to gh-pages
        run: |
          rm -rf gh-pages/*  # 清空 gh-pages 根目录
          cp -r docs/.vitepress/dist/* gh-pages/  # 复制构建输出到根目录

      - name: Commit and push changes to gh-pages
        run: |
          cd gh-pages
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Deploy VitePress site to gh-pages" || echo "No changes to commit"
          git push origin gh-pages
